apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  #Selector defines which pods are going to be respresented by this service
  #The service becomes a network endpoint for either other services
  #... or external users to connect ie via the browser
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      #targetPort: 8080      
      nodePort: 30080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  #Selector defines which pods are going to be respresented by this service
  #The service becomes a network endpoint for either other services
  #... or external users to connect ie via the browser
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010
    
    - name: message-endpoint
      port: 61616

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  #Selector defines which pods are going to be respresented by this service
  #The service becomes a network endpoint for either other services
  #... or external users to connect ie via the browser
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  #Selector defines which pods are going to be respresented by this service
  #The service becomes a network endpoint for either other services
  #... or external users to connect ie via the browser
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080
  type: ClusterIP
